algoritmo "divisão de dois numeros"
// Função :
// Autor :
// Data : 14/08/2017
// Seção de Declarações 
var
 dividendo, divisor, resultado: real
inicio
// Seção de Comandos 

escreval("-------------- Divisão de dois números ----------")
escreva("Entre com o número a ser dividido: ")
leia(dividendo)

escreva("Entre com o número divisor: ")
leia(divisor)

resultado <- dividendo / divisor
escreva("Resultado da sua divisão: ", resultado)


fimalgoritmo
